[package]
name = "magic-converter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
iced = { version = "0.10", features = ["tokio"] }
tokio = { version = "1.36", features = ["full"] }
